/* Generated by make-thunar-vfs-alias.pl. Do not edit this file. */

#ifdef HAVE_GNUC_VISIBILITY

#include <glib.h>

#undef IN_HEADER
#define IN_HEADER(x) 1

#undef IN_SOURCE
#define IN_SOURCE defined

#if IN_HEADER(__THUNAR_VFS_H__)
#if IN_SOURCE(__THUNAR_VFS_C__)
#undef thunar_vfs_init 
extern __typeof (thunar_vfs_init) thunar_vfs_init __attribute((alias("IA__thunar_vfs_init"), visibility("default")));

#undef thunar_vfs_shutdown 
extern __typeof (thunar_vfs_shutdown) thunar_vfs_shutdown __attribute((alias("IA__thunar_vfs_shutdown"), visibility("default")));

#undef thunar_vfs_listdir 
extern __typeof (thunar_vfs_listdir) thunar_vfs_listdir __attribute((alias("IA__thunar_vfs_listdir"), visibility("default")));

#undef thunar_vfs_create_file 
extern __typeof (thunar_vfs_create_file) thunar_vfs_create_file __attribute((alias("IA__thunar_vfs_create_file"), visibility("default")));

#undef thunar_vfs_create_files 
extern __typeof (thunar_vfs_create_files) thunar_vfs_create_files __attribute((alias("IA__thunar_vfs_create_files"), visibility("default")));

#undef thunar_vfs_copy_file 
extern __typeof (thunar_vfs_copy_file) thunar_vfs_copy_file __attribute((alias("IA__thunar_vfs_copy_file"), visibility("default")));

#undef thunar_vfs_copy_files 
extern __typeof (thunar_vfs_copy_files) thunar_vfs_copy_files __attribute((alias("IA__thunar_vfs_copy_files"), visibility("default")));

#undef thunar_vfs_link_file 
extern __typeof (thunar_vfs_link_file) thunar_vfs_link_file __attribute((alias("IA__thunar_vfs_link_file"), visibility("default")));

#undef thunar_vfs_link_files 
extern __typeof (thunar_vfs_link_files) thunar_vfs_link_files __attribute((alias("IA__thunar_vfs_link_files"), visibility("default")));

#undef thunar_vfs_move_file 
extern __typeof (thunar_vfs_move_file) thunar_vfs_move_file __attribute((alias("IA__thunar_vfs_move_file"), visibility("default")));

#undef thunar_vfs_move_files 
extern __typeof (thunar_vfs_move_files) thunar_vfs_move_files __attribute((alias("IA__thunar_vfs_move_files"), visibility("default")));

#undef thunar_vfs_unlink_file 
extern __typeof (thunar_vfs_unlink_file) thunar_vfs_unlink_file __attribute((alias("IA__thunar_vfs_unlink_file"), visibility("default")));

#undef thunar_vfs_unlink_files 
extern __typeof (thunar_vfs_unlink_files) thunar_vfs_unlink_files __attribute((alias("IA__thunar_vfs_unlink_files"), visibility("default")));

#undef thunar_vfs_make_directory 
extern __typeof (thunar_vfs_make_directory) thunar_vfs_make_directory __attribute((alias("IA__thunar_vfs_make_directory"), visibility("default")));

#undef thunar_vfs_make_directories 
extern __typeof (thunar_vfs_make_directories) thunar_vfs_make_directories __attribute((alias("IA__thunar_vfs_make_directories"), visibility("default")));

#undef thunar_vfs_change_mode 
extern __typeof (thunar_vfs_change_mode) thunar_vfs_change_mode __attribute((alias("IA__thunar_vfs_change_mode"), visibility("default")));

#undef thunar_vfs_change_group 
extern __typeof (thunar_vfs_change_group) thunar_vfs_change_group __attribute((alias("IA__thunar_vfs_change_group"), visibility("default")));

#undef thunar_vfs_change_owner 
extern __typeof (thunar_vfs_change_owner) thunar_vfs_change_owner __attribute((alias("IA__thunar_vfs_change_owner"), visibility("default")));

#undef thunar_vfs_deep_count 
extern __typeof (thunar_vfs_deep_count) thunar_vfs_deep_count __attribute((alias("IA__thunar_vfs_deep_count"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_CONFIG_H__)
#if IN_SOURCE(__THUNAR_VFS_CONFIG_C__)
#undef thunar_vfs_major_version 
extern __typeof (thunar_vfs_major_version) thunar_vfs_major_version __attribute((alias("IA__thunar_vfs_major_version"), visibility("default")));

#undef thunar_vfs_minor_version 
extern __typeof (thunar_vfs_minor_version) thunar_vfs_minor_version __attribute((alias("IA__thunar_vfs_minor_version"), visibility("default")));

#undef thunar_vfs_micro_version 
extern __typeof (thunar_vfs_micro_version) thunar_vfs_micro_version __attribute((alias("IA__thunar_vfs_micro_version"), visibility("default")));

#undef thunar_vfs_check_version 
extern __typeof (thunar_vfs_check_version) thunar_vfs_check_version __attribute((alias("IA__thunar_vfs_check_version"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_INFO_H__)
#if IN_SOURCE(__THUNAR_VFS_INFO_C__)
#undef thunar_vfs_info_get_type 
extern __typeof (thunar_vfs_info_get_type) thunar_vfs_info_get_type __attribute((alias("IA__thunar_vfs_info_get_type"), visibility("default")));

#undef thunar_vfs_info_new_for_path 
extern __typeof (thunar_vfs_info_new_for_path) thunar_vfs_info_new_for_path __attribute((alias("IA__thunar_vfs_info_new_for_path"), visibility("default")));

#undef thunar_vfs_info_unref 
extern __typeof (thunar_vfs_info_unref) thunar_vfs_info_unref __attribute((alias("IA__thunar_vfs_info_unref"), visibility("default")));

#undef thunar_vfs_info_copy 
extern __typeof (thunar_vfs_info_copy) thunar_vfs_info_copy __attribute((alias("IA__thunar_vfs_info_copy"), visibility("default")));

#undef thunar_vfs_info_set_custom_icon 
extern __typeof (thunar_vfs_info_set_custom_icon) thunar_vfs_info_set_custom_icon __attribute((alias("IA__thunar_vfs_info_set_custom_icon"), visibility("default")));

#undef thunar_vfs_info_get_free_space 
extern __typeof (thunar_vfs_info_get_free_space) thunar_vfs_info_get_free_space __attribute((alias("IA__thunar_vfs_info_get_free_space"), visibility("default")));

#undef thunar_vfs_info_get_metadata 
extern __typeof (thunar_vfs_info_get_metadata) thunar_vfs_info_get_metadata __attribute((alias("IA__thunar_vfs_info_get_metadata"), visibility("default")));

#undef thunar_vfs_info_execute 
extern __typeof (thunar_vfs_info_execute) thunar_vfs_info_execute __attribute((alias("IA__thunar_vfs_info_execute"), visibility("default")));

#undef thunar_vfs_info_rename 
extern __typeof (thunar_vfs_info_rename) thunar_vfs_info_rename __attribute((alias("IA__thunar_vfs_info_rename"), visibility("default")));

#undef thunar_vfs_info_matches 
extern __typeof (thunar_vfs_info_matches) thunar_vfs_info_matches __attribute((alias("IA__thunar_vfs_info_matches"), visibility("default")));

#undef thunar_vfs_info_list_free 
extern __typeof (thunar_vfs_info_list_free) thunar_vfs_info_list_free __attribute((alias("IA__thunar_vfs_info_list_free"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_ENUM_TYPES_H__)
#if IN_SOURCE(__THUNAR_VFS_ENUM_TYPES_C__)
#undef thunar_vfs_deep_count_flags_get_type 
extern __typeof (thunar_vfs_deep_count_flags_get_type) thunar_vfs_deep_count_flags_get_type __attribute((alias("IA__thunar_vfs_deep_count_flags_get_type"), visibility("default")));

#undef thunar_vfs_file_flags_get_type 
extern __typeof (thunar_vfs_file_flags_get_type) thunar_vfs_file_flags_get_type __attribute((alias("IA__thunar_vfs_file_flags_get_type"), visibility("default")));

#undef thunar_vfs_file_mode_get_type 
extern __typeof (thunar_vfs_file_mode_get_type) thunar_vfs_file_mode_get_type __attribute((alias("IA__thunar_vfs_file_mode_get_type"), visibility("default")));

#undef thunar_vfs_file_type_get_type 
extern __typeof (thunar_vfs_file_type_get_type) thunar_vfs_file_type_get_type __attribute((alias("IA__thunar_vfs_file_type_get_type"), visibility("default")));

#undef thunar_vfs_job_response_get_type 
extern __typeof (thunar_vfs_job_response_get_type) thunar_vfs_job_response_get_type __attribute((alias("IA__thunar_vfs_job_response_get_type"), visibility("default")));

#undef thunar_vfs_mime_handler_flags_get_type 
extern __typeof (thunar_vfs_mime_handler_flags_get_type) thunar_vfs_mime_handler_flags_get_type __attribute((alias("IA__thunar_vfs_mime_handler_flags_get_type"), visibility("default")));

#undef thunar_vfs_monitor_event_get_type 
extern __typeof (thunar_vfs_monitor_event_get_type) thunar_vfs_monitor_event_get_type __attribute((alias("IA__thunar_vfs_monitor_event_get_type"), visibility("default")));

#undef thunar_vfs_thumb_size_get_type 
extern __typeof (thunar_vfs_thumb_size_get_type) thunar_vfs_thumb_size_get_type __attribute((alias("IA__thunar_vfs_thumb_size_get_type"), visibility("default")));

#undef thunar_vfs_volume_kind_get_type 
extern __typeof (thunar_vfs_volume_kind_get_type) thunar_vfs_volume_kind_get_type __attribute((alias("IA__thunar_vfs_volume_kind_get_type"), visibility("default")));

#undef thunar_vfs_volume_status_get_type 
extern __typeof (thunar_vfs_volume_status_get_type) thunar_vfs_volume_status_get_type __attribute((alias("IA__thunar_vfs_volume_status_get_type"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_INTERACTIVE_JOB_H__)
#if IN_SOURCE(__THUNAR_VFS_INTERACTIVE_JOB_C__)
#undef thunar_vfs_interactive_job_response_get_type 
extern __typeof (thunar_vfs_interactive_job_response_get_type) thunar_vfs_interactive_job_response_get_type __attribute((alias("IA__thunar_vfs_interactive_job_response_get_type"), visibility("default")));

#undef thunar_vfs_interactive_job_get_type 
extern __typeof (thunar_vfs_interactive_job_get_type) thunar_vfs_interactive_job_get_type __attribute((alias("IA__thunar_vfs_interactive_job_get_type"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_JOB_H__)
#if IN_SOURCE(__THUNAR_VFS_JOB_C__)
#undef thunar_vfs_job_get_type 
extern __typeof (thunar_vfs_job_get_type) thunar_vfs_job_get_type __attribute((alias("IA__thunar_vfs_job_get_type"), visibility("default")));

#undef thunar_vfs_job_launch 
extern __typeof (thunar_vfs_job_launch) thunar_vfs_job_launch __attribute((alias("IA__thunar_vfs_job_launch"), visibility("default")));

#undef thunar_vfs_job_cancel 
extern __typeof (thunar_vfs_job_cancel) thunar_vfs_job_cancel __attribute((alias("IA__thunar_vfs_job_cancel"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_MIME_ACTION_H__)
#if IN_SOURCE(__THUNAR_VFS_MIME_ACTION_C__)
#undef thunar_vfs_mime_action_get_type 
extern __typeof (thunar_vfs_mime_action_get_type) thunar_vfs_mime_action_get_type __attribute((alias("IA__thunar_vfs_mime_action_get_type"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_MIME_APPLICATION_H__)
#if IN_SOURCE(__THUNAR_VFS_MIME_APPLICATION_C__)
#undef thunar_vfs_mime_application_get_type 
extern __typeof (thunar_vfs_mime_application_get_type) thunar_vfs_mime_application_get_type __attribute((alias("IA__thunar_vfs_mime_application_get_type"), visibility("default")));

#undef thunar_vfs_mime_application_new_from_desktop_id 
extern __typeof (thunar_vfs_mime_application_new_from_desktop_id) thunar_vfs_mime_application_new_from_desktop_id __attribute((alias("IA__thunar_vfs_mime_application_new_from_desktop_id"), visibility("default")));

#undef thunar_vfs_mime_application_new_from_file 
extern __typeof (thunar_vfs_mime_application_new_from_file) thunar_vfs_mime_application_new_from_file __attribute((alias("IA__thunar_vfs_mime_application_new_from_file"), visibility("default")));

#undef thunar_vfs_mime_application_is_usercreated 
extern __typeof (thunar_vfs_mime_application_is_usercreated) thunar_vfs_mime_application_is_usercreated __attribute((alias("IA__thunar_vfs_mime_application_is_usercreated"), visibility("default")));

#undef thunar_vfs_mime_application_get_actions 
extern __typeof (thunar_vfs_mime_application_get_actions) thunar_vfs_mime_application_get_actions __attribute((alias("IA__thunar_vfs_mime_application_get_actions"), visibility("default")));

#undef thunar_vfs_mime_application_get_desktop_id 
extern __typeof (thunar_vfs_mime_application_get_desktop_id) thunar_vfs_mime_application_get_desktop_id __attribute((alias("IA__thunar_vfs_mime_application_get_desktop_id"), visibility("default")));

#undef thunar_vfs_mime_application_get_mime_types 
extern __typeof (thunar_vfs_mime_application_get_mime_types) thunar_vfs_mime_application_get_mime_types __attribute((alias("IA__thunar_vfs_mime_application_get_mime_types"), visibility("default")));

#undef thunar_vfs_mime_application_hash 
extern __typeof (thunar_vfs_mime_application_hash) thunar_vfs_mime_application_hash __attribute((alias("IA__thunar_vfs_mime_application_hash"), visibility("default")));

#undef thunar_vfs_mime_application_equal 
extern __typeof (thunar_vfs_mime_application_equal) thunar_vfs_mime_application_equal __attribute((alias("IA__thunar_vfs_mime_application_equal"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_MIME_DATABASE_H__)
#if IN_SOURCE(__THUNAR_VFS_MIME_DATABASE_C__)
#undef thunar_vfs_mime_database_get_type 
extern __typeof (thunar_vfs_mime_database_get_type) thunar_vfs_mime_database_get_type __attribute((alias("IA__thunar_vfs_mime_database_get_type"), visibility("default")));

#undef thunar_vfs_mime_database_get_default 
extern __typeof (thunar_vfs_mime_database_get_default) thunar_vfs_mime_database_get_default __attribute((alias("IA__thunar_vfs_mime_database_get_default"), visibility("default")));

#undef thunar_vfs_mime_database_get_info 
extern __typeof (thunar_vfs_mime_database_get_info) thunar_vfs_mime_database_get_info __attribute((alias("IA__thunar_vfs_mime_database_get_info"), visibility("default")));

#undef thunar_vfs_mime_database_get_info_for_data 
extern __typeof (thunar_vfs_mime_database_get_info_for_data) thunar_vfs_mime_database_get_info_for_data __attribute((alias("IA__thunar_vfs_mime_database_get_info_for_data"), visibility("default")));

#undef thunar_vfs_mime_database_get_info_for_name 
extern __typeof (thunar_vfs_mime_database_get_info_for_name) thunar_vfs_mime_database_get_info_for_name __attribute((alias("IA__thunar_vfs_mime_database_get_info_for_name"), visibility("default")));

#undef thunar_vfs_mime_database_get_info_for_file 
extern __typeof (thunar_vfs_mime_database_get_info_for_file) thunar_vfs_mime_database_get_info_for_file __attribute((alias("IA__thunar_vfs_mime_database_get_info_for_file"), visibility("default")));

#undef thunar_vfs_mime_database_get_infos_for_info 
extern __typeof (thunar_vfs_mime_database_get_infos_for_info) thunar_vfs_mime_database_get_infos_for_info __attribute((alias("IA__thunar_vfs_mime_database_get_infos_for_info"), visibility("default")));

#undef thunar_vfs_mime_database_get_applications 
extern __typeof (thunar_vfs_mime_database_get_applications) thunar_vfs_mime_database_get_applications __attribute((alias("IA__thunar_vfs_mime_database_get_applications"), visibility("default")));

#undef thunar_vfs_mime_database_get_default_application 
extern __typeof (thunar_vfs_mime_database_get_default_application) thunar_vfs_mime_database_get_default_application __attribute((alias("IA__thunar_vfs_mime_database_get_default_application"), visibility("default")));

#undef thunar_vfs_mime_database_set_default_application 
extern __typeof (thunar_vfs_mime_database_set_default_application) thunar_vfs_mime_database_set_default_application __attribute((alias("IA__thunar_vfs_mime_database_set_default_application"), visibility("default")));

#undef thunar_vfs_mime_database_add_application 
extern __typeof (thunar_vfs_mime_database_add_application) thunar_vfs_mime_database_add_application __attribute((alias("IA__thunar_vfs_mime_database_add_application"), visibility("default")));

#undef thunar_vfs_mime_database_remove_application 
extern __typeof (thunar_vfs_mime_database_remove_application) thunar_vfs_mime_database_remove_application __attribute((alias("IA__thunar_vfs_mime_database_remove_application"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_MIME_HANDLER_H__)
#if IN_SOURCE(__THUNAR_VFS_MIME_HANDLER_C__)
#undef thunar_vfs_mime_handler_get_type 
extern __typeof (thunar_vfs_mime_handler_get_type) thunar_vfs_mime_handler_get_type __attribute((alias("IA__thunar_vfs_mime_handler_get_type"), visibility("default")));

#undef thunar_vfs_mime_handler_get_command 
extern __typeof (thunar_vfs_mime_handler_get_command) thunar_vfs_mime_handler_get_command __attribute((alias("IA__thunar_vfs_mime_handler_get_command"), visibility("default")));

#undef thunar_vfs_mime_handler_get_flags 
extern __typeof (thunar_vfs_mime_handler_get_flags) thunar_vfs_mime_handler_get_flags __attribute((alias("IA__thunar_vfs_mime_handler_get_flags"), visibility("default")));

#undef thunar_vfs_mime_handler_get_name 
extern __typeof (thunar_vfs_mime_handler_get_name) thunar_vfs_mime_handler_get_name __attribute((alias("IA__thunar_vfs_mime_handler_get_name"), visibility("default")));

#undef thunar_vfs_mime_handler_exec 
extern __typeof (thunar_vfs_mime_handler_exec) thunar_vfs_mime_handler_exec __attribute((alias("IA__thunar_vfs_mime_handler_exec"), visibility("default")));

#undef thunar_vfs_mime_handler_exec_with_env 
extern __typeof (thunar_vfs_mime_handler_exec_with_env) thunar_vfs_mime_handler_exec_with_env __attribute((alias("IA__thunar_vfs_mime_handler_exec_with_env"), visibility("default")));

#undef thunar_vfs_mime_handler_lookup_icon_name 
extern __typeof (thunar_vfs_mime_handler_lookup_icon_name) thunar_vfs_mime_handler_lookup_icon_name __attribute((alias("IA__thunar_vfs_mime_handler_lookup_icon_name"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_MIME_INFO_H__)
#if IN_SOURCE(__THUNAR_VFS_MIME_INFO_C__)
#undef thunar_vfs_mime_info_get_type 
extern __typeof (thunar_vfs_mime_info_get_type) thunar_vfs_mime_info_get_type __attribute((alias("IA__thunar_vfs_mime_info_get_type"), visibility("default")));

#undef thunar_vfs_mime_info_new 
extern __typeof (thunar_vfs_mime_info_new) thunar_vfs_mime_info_new __attribute((alias("IA__thunar_vfs_mime_info_new"), visibility("default")));

#undef thunar_vfs_mime_info_unref 
extern __typeof (thunar_vfs_mime_info_unref) thunar_vfs_mime_info_unref __attribute((alias("IA__thunar_vfs_mime_info_unref"), visibility("default")));

#undef thunar_vfs_mime_info_get_comment 
extern __typeof (thunar_vfs_mime_info_get_comment) thunar_vfs_mime_info_get_comment __attribute((alias("IA__thunar_vfs_mime_info_get_comment"), visibility("default")));

#undef thunar_vfs_mime_info_get_media 
extern __typeof (thunar_vfs_mime_info_get_media) thunar_vfs_mime_info_get_media __attribute((alias("IA__thunar_vfs_mime_info_get_media"), visibility("default")));

#undef thunar_vfs_mime_info_get_subtype 
extern __typeof (thunar_vfs_mime_info_get_subtype) thunar_vfs_mime_info_get_subtype __attribute((alias("IA__thunar_vfs_mime_info_get_subtype"), visibility("default")));

#undef thunar_vfs_mime_info_hash 
extern __typeof (thunar_vfs_mime_info_hash) thunar_vfs_mime_info_hash __attribute((alias("IA__thunar_vfs_mime_info_hash"), visibility("default")));

#undef thunar_vfs_mime_info_equal 
extern __typeof (thunar_vfs_mime_info_equal) thunar_vfs_mime_info_equal __attribute((alias("IA__thunar_vfs_mime_info_equal"), visibility("default")));

#undef thunar_vfs_mime_info_lookup_icon_name 
extern __typeof (thunar_vfs_mime_info_lookup_icon_name) thunar_vfs_mime_info_lookup_icon_name __attribute((alias("IA__thunar_vfs_mime_info_lookup_icon_name"), visibility("default")));

#undef thunar_vfs_mime_info_list_free 
extern __typeof (thunar_vfs_mime_info_list_free) thunar_vfs_mime_info_list_free __attribute((alias("IA__thunar_vfs_mime_info_list_free"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_MONITOR_H__)
#if IN_SOURCE(__THUNAR_VFS_MONITOR_C__)
#undef thunar_vfs_monitor_get_type 
extern __typeof (thunar_vfs_monitor_get_type) thunar_vfs_monitor_get_type __attribute((alias("IA__thunar_vfs_monitor_get_type"), visibility("default")));

#undef thunar_vfs_monitor_get_default 
extern __typeof (thunar_vfs_monitor_get_default) thunar_vfs_monitor_get_default __attribute((alias("IA__thunar_vfs_monitor_get_default"), visibility("default")));

#undef thunar_vfs_monitor_add_directory 
extern __typeof (thunar_vfs_monitor_add_directory) thunar_vfs_monitor_add_directory __attribute((alias("IA__thunar_vfs_monitor_add_directory"), visibility("default")));

#undef thunar_vfs_monitor_add_file 
extern __typeof (thunar_vfs_monitor_add_file) thunar_vfs_monitor_add_file __attribute((alias("IA__thunar_vfs_monitor_add_file"), visibility("default")));

#undef thunar_vfs_monitor_remove 
extern __typeof (thunar_vfs_monitor_remove) thunar_vfs_monitor_remove __attribute((alias("IA__thunar_vfs_monitor_remove"), visibility("default")));

#undef thunar_vfs_monitor_feed 
extern __typeof (thunar_vfs_monitor_feed) thunar_vfs_monitor_feed __attribute((alias("IA__thunar_vfs_monitor_feed"), visibility("default")));

#undef thunar_vfs_monitor_wait 
extern __typeof (thunar_vfs_monitor_wait) thunar_vfs_monitor_wait __attribute((alias("IA__thunar_vfs_monitor_wait"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_PATH_H__)
#if IN_SOURCE(__THUNAR_VFS_PATH_C__)
#undef thunar_vfs_path_get_type 
extern __typeof (thunar_vfs_path_get_type) thunar_vfs_path_get_type __attribute((alias("IA__thunar_vfs_path_get_type"), visibility("default")));

#undef thunar_vfs_path_list_get_type 
extern __typeof (thunar_vfs_path_list_get_type) thunar_vfs_path_list_get_type __attribute((alias("IA__thunar_vfs_path_list_get_type"), visibility("default")));

#undef thunar_vfs_path_new 
extern __typeof (thunar_vfs_path_new) thunar_vfs_path_new __attribute((alias("IA__thunar_vfs_path_new"), visibility("default")));

#undef thunar_vfs_path_get_for_home 
extern __typeof (thunar_vfs_path_get_for_home) thunar_vfs_path_get_for_home __attribute((alias("IA__thunar_vfs_path_get_for_home"), visibility("default")));

#undef thunar_vfs_path_get_for_root 
extern __typeof (thunar_vfs_path_get_for_root) thunar_vfs_path_get_for_root __attribute((alias("IA__thunar_vfs_path_get_for_root"), visibility("default")));

#undef thunar_vfs_path_get_for_trash 
extern __typeof (thunar_vfs_path_get_for_trash) thunar_vfs_path_get_for_trash __attribute((alias("IA__thunar_vfs_path_get_for_trash"), visibility("default")));

#undef thunar_vfs_path_unref 
extern __typeof (thunar_vfs_path_unref) thunar_vfs_path_unref __attribute((alias("IA__thunar_vfs_path_unref"), visibility("default")));

#undef thunar_vfs_path_hash 
extern __typeof (thunar_vfs_path_hash) thunar_vfs_path_hash __attribute((alias("IA__thunar_vfs_path_hash"), visibility("default")));

#undef thunar_vfs_path_equal 
extern __typeof (thunar_vfs_path_equal) thunar_vfs_path_equal __attribute((alias("IA__thunar_vfs_path_equal"), visibility("default")));

#undef thunar_vfs_path_relative 
extern __typeof (thunar_vfs_path_relative) thunar_vfs_path_relative __attribute((alias("IA__thunar_vfs_path_relative"), visibility("default")));

#undef thunar_vfs_path_is_ancestor 
extern __typeof (thunar_vfs_path_is_ancestor) thunar_vfs_path_is_ancestor __attribute((alias("IA__thunar_vfs_path_is_ancestor"), visibility("default")));

#undef thunar_vfs_path_is_home 
extern __typeof (thunar_vfs_path_is_home) thunar_vfs_path_is_home __attribute((alias("IA__thunar_vfs_path_is_home"), visibility("default")));

#undef thunar_vfs_path_dup_string 
extern __typeof (thunar_vfs_path_dup_string) thunar_vfs_path_dup_string __attribute((alias("IA__thunar_vfs_path_dup_string"), visibility("default")));

#undef thunar_vfs_path_to_string 
extern __typeof (thunar_vfs_path_to_string) thunar_vfs_path_to_string __attribute((alias("IA__thunar_vfs_path_to_string"), visibility("default")));

#undef thunar_vfs_path_dup_uri 
extern __typeof (thunar_vfs_path_dup_uri) thunar_vfs_path_dup_uri __attribute((alias("IA__thunar_vfs_path_dup_uri"), visibility("default")));

#undef thunar_vfs_path_to_uri 
extern __typeof (thunar_vfs_path_to_uri) thunar_vfs_path_to_uri __attribute((alias("IA__thunar_vfs_path_to_uri"), visibility("default")));

#undef thunar_vfs_path_list_from_string 
extern __typeof (thunar_vfs_path_list_from_string) thunar_vfs_path_list_from_string __attribute((alias("IA__thunar_vfs_path_list_from_string"), visibility("default")));

#undef thunar_vfs_path_list_to_string 
extern __typeof (thunar_vfs_path_list_to_string) thunar_vfs_path_list_to_string __attribute((alias("IA__thunar_vfs_path_list_to_string"), visibility("default")));

#undef thunar_vfs_path_list_copy 
extern __typeof (thunar_vfs_path_list_copy) thunar_vfs_path_list_copy __attribute((alias("IA__thunar_vfs_path_list_copy"), visibility("default")));

#undef thunar_vfs_path_list_free 
extern __typeof (thunar_vfs_path_list_free) thunar_vfs_path_list_free __attribute((alias("IA__thunar_vfs_path_list_free"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_THUMB_H__)
#if IN_SOURCE(__THUNAR_VFS_THUMB_C__)
#undef thunar_vfs_thumb_factory_get_type 
extern __typeof (thunar_vfs_thumb_factory_get_type) thunar_vfs_thumb_factory_get_type __attribute((alias("IA__thunar_vfs_thumb_factory_get_type"), visibility("default")));

#undef thunar_vfs_thumb_factory_new 
extern __typeof (thunar_vfs_thumb_factory_new) thunar_vfs_thumb_factory_new __attribute((alias("IA__thunar_vfs_thumb_factory_new"), visibility("default")));

#undef thunar_vfs_thumb_factory_lookup_thumbnail 
extern __typeof (thunar_vfs_thumb_factory_lookup_thumbnail) thunar_vfs_thumb_factory_lookup_thumbnail __attribute((alias("IA__thunar_vfs_thumb_factory_lookup_thumbnail"), visibility("default")));

#undef thunar_vfs_thumb_factory_can_thumbnail 
extern __typeof (thunar_vfs_thumb_factory_can_thumbnail) thunar_vfs_thumb_factory_can_thumbnail __attribute((alias("IA__thunar_vfs_thumb_factory_can_thumbnail"), visibility("default")));

#undef thunar_vfs_thumb_factory_has_failed_thumbnail 
extern __typeof (thunar_vfs_thumb_factory_has_failed_thumbnail) thunar_vfs_thumb_factory_has_failed_thumbnail __attribute((alias("IA__thunar_vfs_thumb_factory_has_failed_thumbnail"), visibility("default")));

#undef thunar_vfs_thumb_factory_generate_thumbnail 
extern __typeof (thunar_vfs_thumb_factory_generate_thumbnail) thunar_vfs_thumb_factory_generate_thumbnail __attribute((alias("IA__thunar_vfs_thumb_factory_generate_thumbnail"), visibility("default")));

#undef thunar_vfs_thumb_factory_store_thumbnail 
extern __typeof (thunar_vfs_thumb_factory_store_thumbnail) thunar_vfs_thumb_factory_store_thumbnail __attribute((alias("IA__thunar_vfs_thumb_factory_store_thumbnail"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_THUMB_H__)
#if IN_SOURCE(__THUNAR_VFS_THUMB_C__)
#undef thunar_vfs_thumbnail_for_path 
extern __typeof (thunar_vfs_thumbnail_for_path) thunar_vfs_thumbnail_for_path __attribute((alias("IA__thunar_vfs_thumbnail_for_path"), visibility("default")));

#undef thunar_vfs_thumbnail_is_valid 
extern __typeof (thunar_vfs_thumbnail_is_valid) thunar_vfs_thumbnail_is_valid __attribute((alias("IA__thunar_vfs_thumbnail_is_valid"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_USER_H__)
#if IN_SOURCE(__THUNAR_VFS_USER_C__)
#undef thunar_vfs_group_get_type 
extern __typeof (thunar_vfs_group_get_type) thunar_vfs_group_get_type __attribute((alias("IA__thunar_vfs_group_get_type"), visibility("default")));

#undef thunar_vfs_group_get_id 
extern __typeof (thunar_vfs_group_get_id) thunar_vfs_group_get_id __attribute((alias("IA__thunar_vfs_group_get_id"), visibility("default")));

#undef thunar_vfs_group_get_name 
extern __typeof (thunar_vfs_group_get_name) thunar_vfs_group_get_name __attribute((alias("IA__thunar_vfs_group_get_name"), visibility("default")));

#undef thunar_vfs_user_get_type 
extern __typeof (thunar_vfs_user_get_type) thunar_vfs_user_get_type __attribute((alias("IA__thunar_vfs_user_get_type"), visibility("default")));

#undef thunar_vfs_user_get_groups 
extern __typeof (thunar_vfs_user_get_groups) thunar_vfs_user_get_groups __attribute((alias("IA__thunar_vfs_user_get_groups"), visibility("default")));

#undef thunar_vfs_user_get_primary_group 
extern __typeof (thunar_vfs_user_get_primary_group) thunar_vfs_user_get_primary_group __attribute((alias("IA__thunar_vfs_user_get_primary_group"), visibility("default")));

#undef thunar_vfs_user_get_id 
extern __typeof (thunar_vfs_user_get_id) thunar_vfs_user_get_id __attribute((alias("IA__thunar_vfs_user_get_id"), visibility("default")));

#undef thunar_vfs_user_get_name 
extern __typeof (thunar_vfs_user_get_name) thunar_vfs_user_get_name __attribute((alias("IA__thunar_vfs_user_get_name"), visibility("default")));

#undef thunar_vfs_user_get_real_name 
extern __typeof (thunar_vfs_user_get_real_name) thunar_vfs_user_get_real_name __attribute((alias("IA__thunar_vfs_user_get_real_name"), visibility("default")));

#undef thunar_vfs_user_is_me 
extern __typeof (thunar_vfs_user_is_me) thunar_vfs_user_is_me __attribute((alias("IA__thunar_vfs_user_is_me"), visibility("default")));

#undef thunar_vfs_user_manager_get_type 
extern __typeof (thunar_vfs_user_manager_get_type) thunar_vfs_user_manager_get_type __attribute((alias("IA__thunar_vfs_user_manager_get_type"), visibility("default")));

#undef thunar_vfs_user_manager_get_default 
extern __typeof (thunar_vfs_user_manager_get_default) thunar_vfs_user_manager_get_default __attribute((alias("IA__thunar_vfs_user_manager_get_default"), visibility("default")));

#undef thunar_vfs_user_manager_get_group_by_id 
extern __typeof (thunar_vfs_user_manager_get_group_by_id) thunar_vfs_user_manager_get_group_by_id __attribute((alias("IA__thunar_vfs_user_manager_get_group_by_id"), visibility("default")));

#undef thunar_vfs_user_manager_get_user_by_id 
extern __typeof (thunar_vfs_user_manager_get_user_by_id) thunar_vfs_user_manager_get_user_by_id __attribute((alias("IA__thunar_vfs_user_manager_get_user_by_id"), visibility("default")));

#undef thunar_vfs_user_manager_get_all_groups 
extern __typeof (thunar_vfs_user_manager_get_all_groups) thunar_vfs_user_manager_get_all_groups __attribute((alias("IA__thunar_vfs_user_manager_get_all_groups"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_UTIL_H__)
#if IN_SOURCE(__THUNAR_VFS_UTIL_C__)
#undef thunar_vfs_canonicalize_filename 
extern __typeof (thunar_vfs_canonicalize_filename) thunar_vfs_canonicalize_filename __attribute((alias("IA__thunar_vfs_canonicalize_filename"), visibility("default")));

#undef thunar_vfs_expand_filename 
extern __typeof (thunar_vfs_expand_filename) thunar_vfs_expand_filename __attribute((alias("IA__thunar_vfs_expand_filename"), visibility("default")));

#undef thunar_vfs_humanize_size 
extern __typeof (thunar_vfs_humanize_size) thunar_vfs_humanize_size __attribute((alias("IA__thunar_vfs_humanize_size"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_VOLUME_H__)
#if IN_SOURCE(__THUNAR_VFS_VOLUME_C__)
#undef thunar_vfs_volume_get_type 
extern __typeof (thunar_vfs_volume_get_type) thunar_vfs_volume_get_type __attribute((alias("IA__thunar_vfs_volume_get_type"), visibility("default")));

#undef thunar_vfs_volume_get_kind 
extern __typeof (thunar_vfs_volume_get_kind) thunar_vfs_volume_get_kind __attribute((alias("IA__thunar_vfs_volume_get_kind"), visibility("default")));

#undef thunar_vfs_volume_get_name 
extern __typeof (thunar_vfs_volume_get_name) thunar_vfs_volume_get_name __attribute((alias("IA__thunar_vfs_volume_get_name"), visibility("default")));

#undef thunar_vfs_volume_get_status 
extern __typeof (thunar_vfs_volume_get_status) thunar_vfs_volume_get_status __attribute((alias("IA__thunar_vfs_volume_get_status"), visibility("default")));

#undef thunar_vfs_volume_get_mount_point 
extern __typeof (thunar_vfs_volume_get_mount_point) thunar_vfs_volume_get_mount_point __attribute((alias("IA__thunar_vfs_volume_get_mount_point"), visibility("default")));

#undef thunar_vfs_volume_is_disc 
extern __typeof (thunar_vfs_volume_is_disc) thunar_vfs_volume_is_disc __attribute((alias("IA__thunar_vfs_volume_is_disc"), visibility("default")));

#undef thunar_vfs_volume_is_mountable 
extern __typeof (thunar_vfs_volume_is_mountable) thunar_vfs_volume_is_mountable __attribute((alias("IA__thunar_vfs_volume_is_mountable"), visibility("default")));

#undef thunar_vfs_volume_is_mounted 
extern __typeof (thunar_vfs_volume_is_mounted) thunar_vfs_volume_is_mounted __attribute((alias("IA__thunar_vfs_volume_is_mounted"), visibility("default")));

#undef thunar_vfs_volume_is_present 
extern __typeof (thunar_vfs_volume_is_present) thunar_vfs_volume_is_present __attribute((alias("IA__thunar_vfs_volume_is_present"), visibility("default")));

#undef thunar_vfs_volume_is_ejectable 
extern __typeof (thunar_vfs_volume_is_ejectable) thunar_vfs_volume_is_ejectable __attribute((alias("IA__thunar_vfs_volume_is_ejectable"), visibility("default")));

#undef thunar_vfs_volume_is_removable 
extern __typeof (thunar_vfs_volume_is_removable) thunar_vfs_volume_is_removable __attribute((alias("IA__thunar_vfs_volume_is_removable"), visibility("default")));

#undef thunar_vfs_volume_lookup_icon_name 
extern __typeof (thunar_vfs_volume_lookup_icon_name) thunar_vfs_volume_lookup_icon_name __attribute((alias("IA__thunar_vfs_volume_lookup_icon_name"), visibility("default")));

#undef thunar_vfs_volume_eject 
extern __typeof (thunar_vfs_volume_eject) thunar_vfs_volume_eject __attribute((alias("IA__thunar_vfs_volume_eject"), visibility("default")));

#undef thunar_vfs_volume_mount 
extern __typeof (thunar_vfs_volume_mount) thunar_vfs_volume_mount __attribute((alias("IA__thunar_vfs_volume_mount"), visibility("default")));

#undef thunar_vfs_volume_unmount 
extern __typeof (thunar_vfs_volume_unmount) thunar_vfs_volume_unmount __attribute((alias("IA__thunar_vfs_volume_unmount"), visibility("default")));

#endif
#if IN_SOURCE(__THUNAR_VFS_VOLUME_MANAGER_C__)
#undef thunar_vfs_volume_manager_get_type 
extern __typeof (thunar_vfs_volume_manager_get_type) thunar_vfs_volume_manager_get_type __attribute((alias("IA__thunar_vfs_volume_manager_get_type"), visibility("default")));

#undef thunar_vfs_volume_manager_get_default 
extern __typeof (thunar_vfs_volume_manager_get_default) thunar_vfs_volume_manager_get_default __attribute((alias("IA__thunar_vfs_volume_manager_get_default"), visibility("default")));

#undef thunar_vfs_volume_manager_get_volume_by_info 
extern __typeof (thunar_vfs_volume_manager_get_volume_by_info) thunar_vfs_volume_manager_get_volume_by_info __attribute((alias("IA__thunar_vfs_volume_manager_get_volume_by_info"), visibility("default")));

#undef thunar_vfs_volume_manager_get_volumes 
extern __typeof (thunar_vfs_volume_manager_get_volumes) thunar_vfs_volume_manager_get_volumes __attribute((alias("IA__thunar_vfs_volume_manager_get_volumes"), visibility("default")));

#endif
#endif

#endif /* HAVE_GNUC_VISIBILITY */
