/* Generated by make-thunar-vfs-alias.pl. Do not edit this file. */

#ifdef HAVE_GNUC_VISIBILITY

#include <glib.h>

#define IN_HEADER defined
#define IN_SOURCE(x) 1

#if IN_HEADER(__THUNAR_VFS_H__)
#if IN_SOURCE(__THUNAR_VFS_C__)
extern __typeof (thunar_vfs_init) IA__thunar_vfs_init __attribute((visibility("hidden")));
#define thunar_vfs_init IA__thunar_vfs_init

extern __typeof (thunar_vfs_shutdown) IA__thunar_vfs_shutdown __attribute((visibility("hidden")));
#define thunar_vfs_shutdown IA__thunar_vfs_shutdown

extern __typeof (thunar_vfs_listdir) IA__thunar_vfs_listdir __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_listdir IA__thunar_vfs_listdir

extern __typeof (thunar_vfs_create_file) IA__thunar_vfs_create_file __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_create_file IA__thunar_vfs_create_file

extern __typeof (thunar_vfs_create_files) IA__thunar_vfs_create_files __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_create_files IA__thunar_vfs_create_files

extern __typeof (thunar_vfs_copy_file) IA__thunar_vfs_copy_file __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_copy_file IA__thunar_vfs_copy_file

extern __typeof (thunar_vfs_copy_files) IA__thunar_vfs_copy_files __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_copy_files IA__thunar_vfs_copy_files

extern __typeof (thunar_vfs_link_file) IA__thunar_vfs_link_file __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_link_file IA__thunar_vfs_link_file

extern __typeof (thunar_vfs_link_files) IA__thunar_vfs_link_files __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_link_files IA__thunar_vfs_link_files

extern __typeof (thunar_vfs_move_file) IA__thunar_vfs_move_file __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_move_file IA__thunar_vfs_move_file

extern __typeof (thunar_vfs_move_files) IA__thunar_vfs_move_files __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_move_files IA__thunar_vfs_move_files

extern __typeof (thunar_vfs_unlink_file) IA__thunar_vfs_unlink_file __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_unlink_file IA__thunar_vfs_unlink_file

extern __typeof (thunar_vfs_unlink_files) IA__thunar_vfs_unlink_files __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_unlink_files IA__thunar_vfs_unlink_files

extern __typeof (thunar_vfs_make_directory) IA__thunar_vfs_make_directory __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_make_directory IA__thunar_vfs_make_directory

extern __typeof (thunar_vfs_make_directories) IA__thunar_vfs_make_directories __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_make_directories IA__thunar_vfs_make_directories

extern __typeof (thunar_vfs_change_mode) IA__thunar_vfs_change_mode __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_change_mode IA__thunar_vfs_change_mode

extern __typeof (thunar_vfs_change_group) IA__thunar_vfs_change_group __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_change_group IA__thunar_vfs_change_group

extern __typeof (thunar_vfs_change_owner) IA__thunar_vfs_change_owner __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_change_owner IA__thunar_vfs_change_owner

extern __typeof (thunar_vfs_deep_count) IA__thunar_vfs_deep_count __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_deep_count IA__thunar_vfs_deep_count

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_CONFIG_H__)
#if IN_SOURCE(__THUNAR_VFS_CONFIG_C__)
extern __typeof (thunar_vfs_major_version) IA__thunar_vfs_major_version __attribute((visibility("hidden")));
#define thunar_vfs_major_version IA__thunar_vfs_major_version

extern __typeof (thunar_vfs_minor_version) IA__thunar_vfs_minor_version __attribute((visibility("hidden")));
#define thunar_vfs_minor_version IA__thunar_vfs_minor_version

extern __typeof (thunar_vfs_micro_version) IA__thunar_vfs_micro_version __attribute((visibility("hidden")));
#define thunar_vfs_micro_version IA__thunar_vfs_micro_version

extern __typeof (thunar_vfs_check_version) IA__thunar_vfs_check_version __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_check_version IA__thunar_vfs_check_version

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_INFO_H__)
#if IN_SOURCE(__THUNAR_VFS_INFO_C__)
extern __typeof (thunar_vfs_info_get_type) IA__thunar_vfs_info_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_info_get_type IA__thunar_vfs_info_get_type

extern __typeof (thunar_vfs_info_new_for_path) IA__thunar_vfs_info_new_for_path __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_info_new_for_path IA__thunar_vfs_info_new_for_path

extern __typeof (thunar_vfs_info_unref) IA__thunar_vfs_info_unref __attribute((visibility("hidden")));
#define thunar_vfs_info_unref IA__thunar_vfs_info_unref

extern __typeof (thunar_vfs_info_copy) IA__thunar_vfs_info_copy __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_info_copy IA__thunar_vfs_info_copy

extern __typeof (thunar_vfs_info_set_custom_icon) IA__thunar_vfs_info_set_custom_icon __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_info_set_custom_icon IA__thunar_vfs_info_set_custom_icon

extern __typeof (thunar_vfs_info_get_free_space) IA__thunar_vfs_info_get_free_space __attribute((visibility("hidden")));
#define thunar_vfs_info_get_free_space IA__thunar_vfs_info_get_free_space

extern __typeof (thunar_vfs_info_get_metadata) IA__thunar_vfs_info_get_metadata __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_info_get_metadata IA__thunar_vfs_info_get_metadata

extern __typeof (thunar_vfs_info_execute) IA__thunar_vfs_info_execute __attribute((visibility("hidden")));
#define thunar_vfs_info_execute IA__thunar_vfs_info_execute

extern __typeof (thunar_vfs_info_rename) IA__thunar_vfs_info_rename __attribute((visibility("hidden")));
#define thunar_vfs_info_rename IA__thunar_vfs_info_rename

extern __typeof (thunar_vfs_info_matches) IA__thunar_vfs_info_matches __attribute((visibility("hidden")));
#define thunar_vfs_info_matches IA__thunar_vfs_info_matches

extern __typeof (thunar_vfs_info_list_free) IA__thunar_vfs_info_list_free __attribute((visibility("hidden")));
#define thunar_vfs_info_list_free IA__thunar_vfs_info_list_free

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_ENUM_TYPES_H__)
#if IN_SOURCE(__THUNAR_VFS_ENUM_TYPES_C__)
extern __typeof (thunar_vfs_deep_count_flags_get_type) IA__thunar_vfs_deep_count_flags_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_deep_count_flags_get_type IA__thunar_vfs_deep_count_flags_get_type

extern __typeof (thunar_vfs_file_flags_get_type) IA__thunar_vfs_file_flags_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_file_flags_get_type IA__thunar_vfs_file_flags_get_type

extern __typeof (thunar_vfs_file_mode_get_type) IA__thunar_vfs_file_mode_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_file_mode_get_type IA__thunar_vfs_file_mode_get_type

extern __typeof (thunar_vfs_file_type_get_type) IA__thunar_vfs_file_type_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_file_type_get_type IA__thunar_vfs_file_type_get_type

extern __typeof (thunar_vfs_job_response_get_type) IA__thunar_vfs_job_response_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_job_response_get_type IA__thunar_vfs_job_response_get_type

extern __typeof (thunar_vfs_mime_handler_flags_get_type) IA__thunar_vfs_mime_handler_flags_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_mime_handler_flags_get_type IA__thunar_vfs_mime_handler_flags_get_type

extern __typeof (thunar_vfs_monitor_event_get_type) IA__thunar_vfs_monitor_event_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_monitor_event_get_type IA__thunar_vfs_monitor_event_get_type

extern __typeof (thunar_vfs_thumb_size_get_type) IA__thunar_vfs_thumb_size_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_thumb_size_get_type IA__thunar_vfs_thumb_size_get_type

extern __typeof (thunar_vfs_volume_kind_get_type) IA__thunar_vfs_volume_kind_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_volume_kind_get_type IA__thunar_vfs_volume_kind_get_type

extern __typeof (thunar_vfs_volume_status_get_type) IA__thunar_vfs_volume_status_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_volume_status_get_type IA__thunar_vfs_volume_status_get_type

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_INTERACTIVE_JOB_H__)
#if IN_SOURCE(__THUNAR_VFS_INTERACTIVE_JOB_C__)
extern __typeof (thunar_vfs_interactive_job_response_get_type) IA__thunar_vfs_interactive_job_response_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_interactive_job_response_get_type IA__thunar_vfs_interactive_job_response_get_type

extern __typeof (thunar_vfs_interactive_job_get_type) IA__thunar_vfs_interactive_job_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_interactive_job_get_type IA__thunar_vfs_interactive_job_get_type

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_JOB_H__)
#if IN_SOURCE(__THUNAR_VFS_JOB_C__)
extern __typeof (thunar_vfs_job_get_type) IA__thunar_vfs_job_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_job_get_type IA__thunar_vfs_job_get_type

extern __typeof (thunar_vfs_job_launch) IA__thunar_vfs_job_launch __attribute((visibility("hidden")));
#define thunar_vfs_job_launch IA__thunar_vfs_job_launch

extern __typeof (thunar_vfs_job_cancel) IA__thunar_vfs_job_cancel __attribute((visibility("hidden")));
#define thunar_vfs_job_cancel IA__thunar_vfs_job_cancel

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_MIME_ACTION_H__)
#if IN_SOURCE(__THUNAR_VFS_MIME_ACTION_C__)
extern __typeof (thunar_vfs_mime_action_get_type) IA__thunar_vfs_mime_action_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_mime_action_get_type IA__thunar_vfs_mime_action_get_type

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_MIME_APPLICATION_H__)
#if IN_SOURCE(__THUNAR_VFS_MIME_APPLICATION_C__)
extern __typeof (thunar_vfs_mime_application_get_type) IA__thunar_vfs_mime_application_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_mime_application_get_type IA__thunar_vfs_mime_application_get_type

extern __typeof (thunar_vfs_mime_application_new_from_desktop_id) IA__thunar_vfs_mime_application_new_from_desktop_id __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_application_new_from_desktop_id IA__thunar_vfs_mime_application_new_from_desktop_id

extern __typeof (thunar_vfs_mime_application_new_from_file) IA__thunar_vfs_mime_application_new_from_file __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_application_new_from_file IA__thunar_vfs_mime_application_new_from_file

extern __typeof (thunar_vfs_mime_application_is_usercreated) IA__thunar_vfs_mime_application_is_usercreated __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_application_is_usercreated IA__thunar_vfs_mime_application_is_usercreated

extern __typeof (thunar_vfs_mime_application_get_actions) IA__thunar_vfs_mime_application_get_actions __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_application_get_actions IA__thunar_vfs_mime_application_get_actions

extern __typeof (thunar_vfs_mime_application_get_desktop_id) IA__thunar_vfs_mime_application_get_desktop_id __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_application_get_desktop_id IA__thunar_vfs_mime_application_get_desktop_id

extern __typeof (thunar_vfs_mime_application_get_mime_types) IA__thunar_vfs_mime_application_get_mime_types __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_application_get_mime_types IA__thunar_vfs_mime_application_get_mime_types

extern __typeof (thunar_vfs_mime_application_hash) IA__thunar_vfs_mime_application_hash __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_application_hash IA__thunar_vfs_mime_application_hash

extern __typeof (thunar_vfs_mime_application_equal) IA__thunar_vfs_mime_application_equal __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_application_equal IA__thunar_vfs_mime_application_equal

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_MIME_DATABASE_H__)
#if IN_SOURCE(__THUNAR_VFS_MIME_DATABASE_C__)
extern __typeof (thunar_vfs_mime_database_get_type) IA__thunar_vfs_mime_database_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_mime_database_get_type IA__thunar_vfs_mime_database_get_type

extern __typeof (thunar_vfs_mime_database_get_default) IA__thunar_vfs_mime_database_get_default __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_database_get_default IA__thunar_vfs_mime_database_get_default

extern __typeof (thunar_vfs_mime_database_get_info) IA__thunar_vfs_mime_database_get_info __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_database_get_info IA__thunar_vfs_mime_database_get_info

extern __typeof (thunar_vfs_mime_database_get_info_for_data) IA__thunar_vfs_mime_database_get_info_for_data __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_database_get_info_for_data IA__thunar_vfs_mime_database_get_info_for_data

extern __typeof (thunar_vfs_mime_database_get_info_for_name) IA__thunar_vfs_mime_database_get_info_for_name __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_database_get_info_for_name IA__thunar_vfs_mime_database_get_info_for_name

extern __typeof (thunar_vfs_mime_database_get_info_for_file) IA__thunar_vfs_mime_database_get_info_for_file __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_database_get_info_for_file IA__thunar_vfs_mime_database_get_info_for_file

extern __typeof (thunar_vfs_mime_database_get_infos_for_info) IA__thunar_vfs_mime_database_get_infos_for_info __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_database_get_infos_for_info IA__thunar_vfs_mime_database_get_infos_for_info

extern __typeof (thunar_vfs_mime_database_get_applications) IA__thunar_vfs_mime_database_get_applications __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_database_get_applications IA__thunar_vfs_mime_database_get_applications

extern __typeof (thunar_vfs_mime_database_get_default_application) IA__thunar_vfs_mime_database_get_default_application __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_database_get_default_application IA__thunar_vfs_mime_database_get_default_application

extern __typeof (thunar_vfs_mime_database_set_default_application) IA__thunar_vfs_mime_database_set_default_application __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_database_set_default_application IA__thunar_vfs_mime_database_set_default_application

extern __typeof (thunar_vfs_mime_database_add_application) IA__thunar_vfs_mime_database_add_application __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_database_add_application IA__thunar_vfs_mime_database_add_application

extern __typeof (thunar_vfs_mime_database_remove_application) IA__thunar_vfs_mime_database_remove_application __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_database_remove_application IA__thunar_vfs_mime_database_remove_application

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_MIME_HANDLER_H__)
#if IN_SOURCE(__THUNAR_VFS_MIME_HANDLER_C__)
extern __typeof (thunar_vfs_mime_handler_get_type) IA__thunar_vfs_mime_handler_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_mime_handler_get_type IA__thunar_vfs_mime_handler_get_type

extern __typeof (thunar_vfs_mime_handler_get_command) IA__thunar_vfs_mime_handler_get_command __attribute((visibility("hidden")));
#define thunar_vfs_mime_handler_get_command IA__thunar_vfs_mime_handler_get_command

extern __typeof (thunar_vfs_mime_handler_get_flags) IA__thunar_vfs_mime_handler_get_flags __attribute((visibility("hidden")));
#define thunar_vfs_mime_handler_get_flags IA__thunar_vfs_mime_handler_get_flags

extern __typeof (thunar_vfs_mime_handler_get_name) IA__thunar_vfs_mime_handler_get_name __attribute((visibility("hidden")));
#define thunar_vfs_mime_handler_get_name IA__thunar_vfs_mime_handler_get_name

extern __typeof (thunar_vfs_mime_handler_exec) IA__thunar_vfs_mime_handler_exec __attribute((visibility("hidden")));
#define thunar_vfs_mime_handler_exec IA__thunar_vfs_mime_handler_exec

extern __typeof (thunar_vfs_mime_handler_exec_with_env) IA__thunar_vfs_mime_handler_exec_with_env __attribute((visibility("hidden")));
#define thunar_vfs_mime_handler_exec_with_env IA__thunar_vfs_mime_handler_exec_with_env

extern __typeof (thunar_vfs_mime_handler_lookup_icon_name) IA__thunar_vfs_mime_handler_lookup_icon_name __attribute((visibility("hidden")));
#define thunar_vfs_mime_handler_lookup_icon_name IA__thunar_vfs_mime_handler_lookup_icon_name

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_MIME_INFO_H__)
#if IN_SOURCE(__THUNAR_VFS_MIME_INFO_C__)
extern __typeof (thunar_vfs_mime_info_get_type) IA__thunar_vfs_mime_info_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_mime_info_get_type IA__thunar_vfs_mime_info_get_type

extern __typeof (thunar_vfs_mime_info_new) IA__thunar_vfs_mime_info_new __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_info_new IA__thunar_vfs_mime_info_new

extern __typeof (thunar_vfs_mime_info_unref) IA__thunar_vfs_mime_info_unref __attribute((visibility("hidden")));
#define thunar_vfs_mime_info_unref IA__thunar_vfs_mime_info_unref

extern __typeof (thunar_vfs_mime_info_get_comment) IA__thunar_vfs_mime_info_get_comment __attribute((visibility("hidden")));
#define thunar_vfs_mime_info_get_comment IA__thunar_vfs_mime_info_get_comment

extern __typeof (thunar_vfs_mime_info_get_media) IA__thunar_vfs_mime_info_get_media __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_info_get_media IA__thunar_vfs_mime_info_get_media

extern __typeof (thunar_vfs_mime_info_get_subtype) IA__thunar_vfs_mime_info_get_subtype __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_mime_info_get_subtype IA__thunar_vfs_mime_info_get_subtype

extern __typeof (thunar_vfs_mime_info_hash) IA__thunar_vfs_mime_info_hash __attribute((visibility("hidden")));
#define thunar_vfs_mime_info_hash IA__thunar_vfs_mime_info_hash

extern __typeof (thunar_vfs_mime_info_equal) IA__thunar_vfs_mime_info_equal __attribute((visibility("hidden")));
#define thunar_vfs_mime_info_equal IA__thunar_vfs_mime_info_equal

extern __typeof (thunar_vfs_mime_info_lookup_icon_name) IA__thunar_vfs_mime_info_lookup_icon_name __attribute((visibility("hidden")));
#define thunar_vfs_mime_info_lookup_icon_name IA__thunar_vfs_mime_info_lookup_icon_name

extern __typeof (thunar_vfs_mime_info_list_free) IA__thunar_vfs_mime_info_list_free __attribute((visibility("hidden")));
#define thunar_vfs_mime_info_list_free IA__thunar_vfs_mime_info_list_free

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_MONITOR_H__)
#if IN_SOURCE(__THUNAR_VFS_MONITOR_C__)
extern __typeof (thunar_vfs_monitor_get_type) IA__thunar_vfs_monitor_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_monitor_get_type IA__thunar_vfs_monitor_get_type

extern __typeof (thunar_vfs_monitor_get_default) IA__thunar_vfs_monitor_get_default __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_monitor_get_default IA__thunar_vfs_monitor_get_default

extern __typeof (thunar_vfs_monitor_add_directory) IA__thunar_vfs_monitor_add_directory __attribute((visibility("hidden")));
#define thunar_vfs_monitor_add_directory IA__thunar_vfs_monitor_add_directory

extern __typeof (thunar_vfs_monitor_add_file) IA__thunar_vfs_monitor_add_file __attribute((visibility("hidden")));
#define thunar_vfs_monitor_add_file IA__thunar_vfs_monitor_add_file

extern __typeof (thunar_vfs_monitor_remove) IA__thunar_vfs_monitor_remove __attribute((visibility("hidden")));
#define thunar_vfs_monitor_remove IA__thunar_vfs_monitor_remove

extern __typeof (thunar_vfs_monitor_feed) IA__thunar_vfs_monitor_feed __attribute((visibility("hidden")));
#define thunar_vfs_monitor_feed IA__thunar_vfs_monitor_feed

extern __typeof (thunar_vfs_monitor_wait) IA__thunar_vfs_monitor_wait __attribute((visibility("hidden")));
#define thunar_vfs_monitor_wait IA__thunar_vfs_monitor_wait

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_PATH_H__)
#if IN_SOURCE(__THUNAR_VFS_PATH_C__)
extern __typeof (thunar_vfs_path_get_type) IA__thunar_vfs_path_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_path_get_type IA__thunar_vfs_path_get_type

extern __typeof (thunar_vfs_path_list_get_type) IA__thunar_vfs_path_list_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_path_list_get_type IA__thunar_vfs_path_list_get_type

extern __typeof (thunar_vfs_path_new) IA__thunar_vfs_path_new __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_path_new IA__thunar_vfs_path_new

extern __typeof (thunar_vfs_path_get_for_home) IA__thunar_vfs_path_get_for_home __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_path_get_for_home IA__thunar_vfs_path_get_for_home

extern __typeof (thunar_vfs_path_get_for_root) IA__thunar_vfs_path_get_for_root __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_path_get_for_root IA__thunar_vfs_path_get_for_root

extern __typeof (thunar_vfs_path_get_for_trash) IA__thunar_vfs_path_get_for_trash __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_path_get_for_trash IA__thunar_vfs_path_get_for_trash

extern __typeof (thunar_vfs_path_unref) IA__thunar_vfs_path_unref __attribute((visibility("hidden")));
#define thunar_vfs_path_unref IA__thunar_vfs_path_unref

extern __typeof (thunar_vfs_path_hash) IA__thunar_vfs_path_hash __attribute((visibility("hidden")));
#define thunar_vfs_path_hash IA__thunar_vfs_path_hash

extern __typeof (thunar_vfs_path_equal) IA__thunar_vfs_path_equal __attribute((visibility("hidden")));
#define thunar_vfs_path_equal IA__thunar_vfs_path_equal

extern __typeof (thunar_vfs_path_relative) IA__thunar_vfs_path_relative __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_path_relative IA__thunar_vfs_path_relative

extern __typeof (thunar_vfs_path_is_ancestor) IA__thunar_vfs_path_is_ancestor __attribute((visibility("hidden")));
#define thunar_vfs_path_is_ancestor IA__thunar_vfs_path_is_ancestor

extern __typeof (thunar_vfs_path_is_home) IA__thunar_vfs_path_is_home __attribute((visibility("hidden")));
#define thunar_vfs_path_is_home IA__thunar_vfs_path_is_home

extern __typeof (thunar_vfs_path_dup_string) IA__thunar_vfs_path_dup_string __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_path_dup_string IA__thunar_vfs_path_dup_string

extern __typeof (thunar_vfs_path_to_string) IA__thunar_vfs_path_to_string __attribute((visibility("hidden")));
#define thunar_vfs_path_to_string IA__thunar_vfs_path_to_string

extern __typeof (thunar_vfs_path_dup_uri) IA__thunar_vfs_path_dup_uri __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_path_dup_uri IA__thunar_vfs_path_dup_uri

extern __typeof (thunar_vfs_path_to_uri) IA__thunar_vfs_path_to_uri __attribute((visibility("hidden")));
#define thunar_vfs_path_to_uri IA__thunar_vfs_path_to_uri

extern __typeof (thunar_vfs_path_list_from_string) IA__thunar_vfs_path_list_from_string __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_path_list_from_string IA__thunar_vfs_path_list_from_string

extern __typeof (thunar_vfs_path_list_to_string) IA__thunar_vfs_path_list_to_string __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_path_list_to_string IA__thunar_vfs_path_list_to_string

extern __typeof (thunar_vfs_path_list_copy) IA__thunar_vfs_path_list_copy __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_path_list_copy IA__thunar_vfs_path_list_copy

extern __typeof (thunar_vfs_path_list_free) IA__thunar_vfs_path_list_free __attribute((visibility("hidden")));
#define thunar_vfs_path_list_free IA__thunar_vfs_path_list_free

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_THUMB_H__)
#if IN_SOURCE(__THUNAR_VFS_THUMB_C__)
extern __typeof (thunar_vfs_thumb_factory_get_type) IA__thunar_vfs_thumb_factory_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_thumb_factory_get_type IA__thunar_vfs_thumb_factory_get_type

extern __typeof (thunar_vfs_thumb_factory_new) IA__thunar_vfs_thumb_factory_new __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_thumb_factory_new IA__thunar_vfs_thumb_factory_new

extern __typeof (thunar_vfs_thumb_factory_lookup_thumbnail) IA__thunar_vfs_thumb_factory_lookup_thumbnail __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_thumb_factory_lookup_thumbnail IA__thunar_vfs_thumb_factory_lookup_thumbnail

extern __typeof (thunar_vfs_thumb_factory_can_thumbnail) IA__thunar_vfs_thumb_factory_can_thumbnail __attribute((visibility("hidden")));
#define thunar_vfs_thumb_factory_can_thumbnail IA__thunar_vfs_thumb_factory_can_thumbnail

extern __typeof (thunar_vfs_thumb_factory_has_failed_thumbnail) IA__thunar_vfs_thumb_factory_has_failed_thumbnail __attribute((visibility("hidden")));
#define thunar_vfs_thumb_factory_has_failed_thumbnail IA__thunar_vfs_thumb_factory_has_failed_thumbnail

extern __typeof (thunar_vfs_thumb_factory_generate_thumbnail) IA__thunar_vfs_thumb_factory_generate_thumbnail __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_thumb_factory_generate_thumbnail IA__thunar_vfs_thumb_factory_generate_thumbnail

extern __typeof (thunar_vfs_thumb_factory_store_thumbnail) IA__thunar_vfs_thumb_factory_store_thumbnail __attribute((visibility("hidden")));
#define thunar_vfs_thumb_factory_store_thumbnail IA__thunar_vfs_thumb_factory_store_thumbnail

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_THUMB_H__)
#if IN_SOURCE(__THUNAR_VFS_THUMB_C__)
extern __typeof (thunar_vfs_thumbnail_for_path) IA__thunar_vfs_thumbnail_for_path __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_thumbnail_for_path IA__thunar_vfs_thumbnail_for_path

extern __typeof (thunar_vfs_thumbnail_is_valid) IA__thunar_vfs_thumbnail_is_valid __attribute((visibility("hidden")));
#define thunar_vfs_thumbnail_is_valid IA__thunar_vfs_thumbnail_is_valid

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_USER_H__)
#if IN_SOURCE(__THUNAR_VFS_USER_C__)
extern __typeof (thunar_vfs_group_get_type) IA__thunar_vfs_group_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_group_get_type IA__thunar_vfs_group_get_type

extern __typeof (thunar_vfs_group_get_id) IA__thunar_vfs_group_get_id __attribute((visibility("hidden")));
#define thunar_vfs_group_get_id IA__thunar_vfs_group_get_id

extern __typeof (thunar_vfs_group_get_name) IA__thunar_vfs_group_get_name __attribute((visibility("hidden")));
#define thunar_vfs_group_get_name IA__thunar_vfs_group_get_name

extern __typeof (thunar_vfs_user_get_type) IA__thunar_vfs_user_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_user_get_type IA__thunar_vfs_user_get_type

extern __typeof (thunar_vfs_user_get_groups) IA__thunar_vfs_user_get_groups __attribute((visibility("hidden")));
#define thunar_vfs_user_get_groups IA__thunar_vfs_user_get_groups

extern __typeof (thunar_vfs_user_get_primary_group) IA__thunar_vfs_user_get_primary_group __attribute((visibility("hidden")));
#define thunar_vfs_user_get_primary_group IA__thunar_vfs_user_get_primary_group

extern __typeof (thunar_vfs_user_get_id) IA__thunar_vfs_user_get_id __attribute((visibility("hidden")));
#define thunar_vfs_user_get_id IA__thunar_vfs_user_get_id

extern __typeof (thunar_vfs_user_get_name) IA__thunar_vfs_user_get_name __attribute((visibility("hidden")));
#define thunar_vfs_user_get_name IA__thunar_vfs_user_get_name

extern __typeof (thunar_vfs_user_get_real_name) IA__thunar_vfs_user_get_real_name __attribute((visibility("hidden")));
#define thunar_vfs_user_get_real_name IA__thunar_vfs_user_get_real_name

extern __typeof (thunar_vfs_user_is_me) IA__thunar_vfs_user_is_me __attribute((visibility("hidden")));
#define thunar_vfs_user_is_me IA__thunar_vfs_user_is_me

extern __typeof (thunar_vfs_user_manager_get_type) IA__thunar_vfs_user_manager_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_user_manager_get_type IA__thunar_vfs_user_manager_get_type

extern __typeof (thunar_vfs_user_manager_get_default) IA__thunar_vfs_user_manager_get_default __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_user_manager_get_default IA__thunar_vfs_user_manager_get_default

extern __typeof (thunar_vfs_user_manager_get_group_by_id) IA__thunar_vfs_user_manager_get_group_by_id __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_user_manager_get_group_by_id IA__thunar_vfs_user_manager_get_group_by_id

extern __typeof (thunar_vfs_user_manager_get_user_by_id) IA__thunar_vfs_user_manager_get_user_by_id __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_user_manager_get_user_by_id IA__thunar_vfs_user_manager_get_user_by_id

extern __typeof (thunar_vfs_user_manager_get_all_groups) IA__thunar_vfs_user_manager_get_all_groups __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_user_manager_get_all_groups IA__thunar_vfs_user_manager_get_all_groups

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_UTIL_H__)
#if IN_SOURCE(__THUNAR_VFS_UTIL_C__)
extern __typeof (thunar_vfs_canonicalize_filename) IA__thunar_vfs_canonicalize_filename __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_canonicalize_filename IA__thunar_vfs_canonicalize_filename

extern __typeof (thunar_vfs_expand_filename) IA__thunar_vfs_expand_filename __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunar_vfs_expand_filename IA__thunar_vfs_expand_filename

extern __typeof (thunar_vfs_humanize_size) IA__thunar_vfs_humanize_size __attribute((visibility("hidden")));
#define thunar_vfs_humanize_size IA__thunar_vfs_humanize_size

#endif
#endif
#if IN_HEADER(__THUNAR_VFS_VOLUME_H__)
#if IN_SOURCE(__THUNAR_VFS_VOLUME_C__)
extern __typeof (thunar_vfs_volume_get_type) IA__thunar_vfs_volume_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_volume_get_type IA__thunar_vfs_volume_get_type

extern __typeof (thunar_vfs_volume_get_kind) IA__thunar_vfs_volume_get_kind __attribute((visibility("hidden")));
#define thunar_vfs_volume_get_kind IA__thunar_vfs_volume_get_kind

extern __typeof (thunar_vfs_volume_get_name) IA__thunar_vfs_volume_get_name __attribute((visibility("hidden")));
#define thunar_vfs_volume_get_name IA__thunar_vfs_volume_get_name

extern __typeof (thunar_vfs_volume_get_status) IA__thunar_vfs_volume_get_status __attribute((visibility("hidden")));
#define thunar_vfs_volume_get_status IA__thunar_vfs_volume_get_status

extern __typeof (thunar_vfs_volume_get_mount_point) IA__thunar_vfs_volume_get_mount_point __attribute((visibility("hidden")));
#define thunar_vfs_volume_get_mount_point IA__thunar_vfs_volume_get_mount_point

extern __typeof (thunar_vfs_volume_is_disc) IA__thunar_vfs_volume_is_disc __attribute((visibility("hidden")));
#define thunar_vfs_volume_is_disc IA__thunar_vfs_volume_is_disc

extern __typeof (thunar_vfs_volume_is_mountable) IA__thunar_vfs_volume_is_mountable __attribute((visibility("hidden")));
#define thunar_vfs_volume_is_mountable IA__thunar_vfs_volume_is_mountable

extern __typeof (thunar_vfs_volume_is_mounted) IA__thunar_vfs_volume_is_mounted __attribute((visibility("hidden")));
#define thunar_vfs_volume_is_mounted IA__thunar_vfs_volume_is_mounted

extern __typeof (thunar_vfs_volume_is_present) IA__thunar_vfs_volume_is_present __attribute((visibility("hidden")));
#define thunar_vfs_volume_is_present IA__thunar_vfs_volume_is_present

extern __typeof (thunar_vfs_volume_is_ejectable) IA__thunar_vfs_volume_is_ejectable __attribute((visibility("hidden")));
#define thunar_vfs_volume_is_ejectable IA__thunar_vfs_volume_is_ejectable

extern __typeof (thunar_vfs_volume_is_removable) IA__thunar_vfs_volume_is_removable __attribute((visibility("hidden")));
#define thunar_vfs_volume_is_removable IA__thunar_vfs_volume_is_removable

extern __typeof (thunar_vfs_volume_lookup_icon_name) IA__thunar_vfs_volume_lookup_icon_name __attribute((visibility("hidden")));
#define thunar_vfs_volume_lookup_icon_name IA__thunar_vfs_volume_lookup_icon_name

extern __typeof (thunar_vfs_volume_eject) IA__thunar_vfs_volume_eject __attribute((visibility("hidden")));
#define thunar_vfs_volume_eject IA__thunar_vfs_volume_eject

extern __typeof (thunar_vfs_volume_mount) IA__thunar_vfs_volume_mount __attribute((visibility("hidden")));
#define thunar_vfs_volume_mount IA__thunar_vfs_volume_mount

extern __typeof (thunar_vfs_volume_unmount) IA__thunar_vfs_volume_unmount __attribute((visibility("hidden")));
#define thunar_vfs_volume_unmount IA__thunar_vfs_volume_unmount

#endif
#if IN_SOURCE(__THUNAR_VFS_VOLUME_MANAGER_C__)
extern __typeof (thunar_vfs_volume_manager_get_type) IA__thunar_vfs_volume_manager_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunar_vfs_volume_manager_get_type IA__thunar_vfs_volume_manager_get_type

extern __typeof (thunar_vfs_volume_manager_get_default) IA__thunar_vfs_volume_manager_get_default __attribute((visibility("hidden")));
#define thunar_vfs_volume_manager_get_default IA__thunar_vfs_volume_manager_get_default

extern __typeof (thunar_vfs_volume_manager_get_volume_by_info) IA__thunar_vfs_volume_manager_get_volume_by_info __attribute((visibility("hidden")));
#define thunar_vfs_volume_manager_get_volume_by_info IA__thunar_vfs_volume_manager_get_volume_by_info

extern __typeof (thunar_vfs_volume_manager_get_volumes) IA__thunar_vfs_volume_manager_get_volumes __attribute((visibility("hidden")));
#define thunar_vfs_volume_manager_get_volumes IA__thunar_vfs_volume_manager_get_volumes

#endif
#endif

#endif /* HAVE_GNUC_VISIBILITY */
