/* Generated by make-thunarx-alias.pl. Do not edit this file. */

#ifdef HAVE_GNUC_VISIBILITY

#include <glib.h>

#define IN_HEADER defined
#define IN_SOURCE(x) 1

#if IN_HEADER(__THUNARX_CONFIG_H__)
#if IN_SOURCE(__THUNARX_CONFIG_C__)
extern __typeof (thunarx_major_version) IA__thunarx_major_version __attribute((visibility("hidden")));
#define thunarx_major_version IA__thunarx_major_version

extern __typeof (thunarx_minor_version) IA__thunarx_minor_version __attribute((visibility("hidden")));
#define thunarx_minor_version IA__thunarx_minor_version

extern __typeof (thunarx_micro_version) IA__thunarx_micro_version __attribute((visibility("hidden")));
#define thunarx_micro_version IA__thunarx_micro_version

extern __typeof (thunarx_check_version) IA__thunarx_check_version __attribute((visibility("hidden")));
#define thunarx_check_version IA__thunarx_check_version

#endif
#endif
#if IN_HEADER(__THUNARX_FILE_INFO_H__)
#if IN_SOURCE(__THUNARX_FILE_INFO_C__)
extern __typeof (thunarx_file_info_get_type) IA__thunarx_file_info_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunarx_file_info_get_type IA__thunarx_file_info_get_type

extern __typeof (thunarx_file_info_get_name) IA__thunarx_file_info_get_name __attribute((visibility("hidden")));
#define thunarx_file_info_get_name IA__thunarx_file_info_get_name

extern __typeof (thunarx_file_info_get_uri) IA__thunarx_file_info_get_uri __attribute((visibility("hidden")));
#define thunarx_file_info_get_uri IA__thunarx_file_info_get_uri

extern __typeof (thunarx_file_info_get_parent_uri) IA__thunarx_file_info_get_parent_uri __attribute((visibility("hidden")));
#define thunarx_file_info_get_parent_uri IA__thunarx_file_info_get_parent_uri

extern __typeof (thunarx_file_info_get_uri_scheme) IA__thunarx_file_info_get_uri_scheme __attribute((visibility("hidden")));
#define thunarx_file_info_get_uri_scheme IA__thunarx_file_info_get_uri_scheme

extern __typeof (thunarx_file_info_get_mime_type) IA__thunarx_file_info_get_mime_type __attribute((visibility("hidden")));
#define thunarx_file_info_get_mime_type IA__thunarx_file_info_get_mime_type

extern __typeof (thunarx_file_info_has_mime_type) IA__thunarx_file_info_has_mime_type __attribute((visibility("hidden")));
#define thunarx_file_info_has_mime_type IA__thunarx_file_info_has_mime_type

extern __typeof (thunarx_file_info_is_directory) IA__thunarx_file_info_is_directory __attribute((visibility("hidden")));
#define thunarx_file_info_is_directory IA__thunarx_file_info_is_directory

extern __typeof (thunarx_file_info_get_vfs_info) IA__thunarx_file_info_get_vfs_info __attribute((visibility("hidden")));
#define thunarx_file_info_get_vfs_info IA__thunarx_file_info_get_vfs_info

extern __typeof (thunarx_file_info_changed) IA__thunarx_file_info_changed __attribute((visibility("hidden")));
#define thunarx_file_info_changed IA__thunarx_file_info_changed

extern __typeof (thunarx_file_info_renamed) IA__thunarx_file_info_renamed __attribute((visibility("hidden")));
#define thunarx_file_info_renamed IA__thunarx_file_info_renamed

extern __typeof (thunarx_file_info_list_get_type) IA__thunarx_file_info_list_get_type __attribute((visibility("hidden")));
#define thunarx_file_info_list_get_type IA__thunarx_file_info_list_get_type

extern __typeof (thunarx_file_info_list_copy) IA__thunarx_file_info_list_copy __attribute((visibility("hidden")));
#define thunarx_file_info_list_copy IA__thunarx_file_info_list_copy

extern __typeof (thunarx_file_info_list_free) IA__thunarx_file_info_list_free __attribute((visibility("hidden")));
#define thunarx_file_info_list_free IA__thunarx_file_info_list_free

#endif
#endif
#if IN_HEADER(__THUNARX_MENU_PROVIDER_H__)
#if IN_SOURCE(__THUNARX_MENU_PROVIDER_C__)
extern __typeof (thunarx_menu_provider_get_type) IA__thunarx_menu_provider_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunarx_menu_provider_get_type IA__thunarx_menu_provider_get_type

extern __typeof (thunarx_menu_provider_get_file_actions) IA__thunarx_menu_provider_get_file_actions __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunarx_menu_provider_get_file_actions IA__thunarx_menu_provider_get_file_actions

extern __typeof (thunarx_menu_provider_get_folder_actions) IA__thunarx_menu_provider_get_folder_actions __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunarx_menu_provider_get_folder_actions IA__thunarx_menu_provider_get_folder_actions

extern __typeof (thunarx_menu_provider_get_dnd_actions) IA__thunarx_menu_provider_get_dnd_actions __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define thunarx_menu_provider_get_dnd_actions IA__thunarx_menu_provider_get_dnd_actions

#endif
#endif
#if IN_HEADER(__THUNARX_PREFERENCES_PROVIDER_H__)
#if IN_SOURCE(__THUNARX_PREFERENCES_PROVIDER_C__)
extern __typeof (thunarx_preferences_provider_get_type) IA__thunarx_preferences_provider_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunarx_preferences_provider_get_type IA__thunarx_preferences_provider_get_type

extern __typeof (thunarx_preferences_provider_get_actions) IA__thunarx_preferences_provider_get_actions __attribute((visibility("hidden")));
#define thunarx_preferences_provider_get_actions IA__thunarx_preferences_provider_get_actions

#endif
#endif
#if IN_HEADER(__THUNARX_PROPERTY_PAGE_H__)
#if IN_SOURCE(__THUNARX_PROPERTY_PAGE_C__)
extern __typeof (thunarx_property_page_get_type) IA__thunarx_property_page_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunarx_property_page_get_type IA__thunarx_property_page_get_type

extern __typeof (thunarx_property_page_new) IA__thunarx_property_page_new __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define thunarx_property_page_new IA__thunarx_property_page_new

extern __typeof (thunarx_property_page_new_with_label_widget) IA__thunarx_property_page_new_with_label_widget __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define thunarx_property_page_new_with_label_widget IA__thunarx_property_page_new_with_label_widget

extern __typeof (thunarx_property_page_get_label) IA__thunarx_property_page_get_label __attribute((visibility("hidden")));
#define thunarx_property_page_get_label IA__thunarx_property_page_get_label

extern __typeof (thunarx_property_page_set_label) IA__thunarx_property_page_set_label __attribute((visibility("hidden")));
#define thunarx_property_page_set_label IA__thunarx_property_page_set_label

extern __typeof (thunarx_property_page_get_label_widget) IA__thunarx_property_page_get_label_widget __attribute((visibility("hidden")));
#define thunarx_property_page_get_label_widget IA__thunarx_property_page_get_label_widget

extern __typeof (thunarx_property_page_set_label_widget) IA__thunarx_property_page_set_label_widget __attribute((visibility("hidden")));
#define thunarx_property_page_set_label_widget IA__thunarx_property_page_set_label_widget

#endif
#endif
#if IN_HEADER(__THUNARX_PROPERTY_PAGE_PROVIDER_H__)
#if IN_SOURCE(__THUNARX_PROPERTY_PAGE_PROVIDER_C__)
extern __typeof (thunarx_property_page_provider_get_type) IA__thunarx_property_page_provider_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunarx_property_page_provider_get_type IA__thunarx_property_page_provider_get_type

extern __typeof (thunarx_property_page_provider_get_pages) IA__thunarx_property_page_provider_get_pages __attribute((visibility("hidden")));
#define thunarx_property_page_provider_get_pages IA__thunarx_property_page_provider_get_pages

#endif
#endif
#if IN_HEADER(__THUNARX_PROVIDER_FACTORY_H__)
#if IN_SOURCE(__THUNARX_PROVIDER_FACTORY_C__)
extern __typeof (thunarx_provider_factory_get_type) IA__thunarx_provider_factory_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunarx_provider_factory_get_type IA__thunarx_provider_factory_get_type

extern __typeof (thunarx_provider_factory_get_default) IA__thunarx_provider_factory_get_default __attribute((visibility("hidden")));
#define thunarx_provider_factory_get_default IA__thunarx_provider_factory_get_default

extern __typeof (thunarx_provider_factory_list_providers) IA__thunarx_provider_factory_list_providers __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define thunarx_provider_factory_list_providers IA__thunarx_provider_factory_list_providers

#endif
#endif
#if IN_HEADER(__THUNARX_PROVIDER_PLUGIN_H__)
#if IN_SOURCE(__THUNARX_PROVIDER_PLUGIN_C__)
extern __typeof (thunarx_provider_plugin_get_type) IA__thunarx_provider_plugin_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunarx_provider_plugin_get_type IA__thunarx_provider_plugin_get_type

extern __typeof (thunarx_provider_plugin_get_resident) IA__thunarx_provider_plugin_get_resident __attribute((visibility("hidden")));
#define thunarx_provider_plugin_get_resident IA__thunarx_provider_plugin_get_resident

extern __typeof (thunarx_provider_plugin_set_resident) IA__thunarx_provider_plugin_set_resident __attribute((visibility("hidden")));
#define thunarx_provider_plugin_set_resident IA__thunarx_provider_plugin_set_resident

extern __typeof (thunarx_provider_plugin_register_type) IA__thunarx_provider_plugin_register_type __attribute((visibility("hidden")));
#define thunarx_provider_plugin_register_type IA__thunarx_provider_plugin_register_type

extern __typeof (thunarx_provider_plugin_add_interface) IA__thunarx_provider_plugin_add_interface __attribute((visibility("hidden")));
#define thunarx_provider_plugin_add_interface IA__thunarx_provider_plugin_add_interface

extern __typeof (thunarx_provider_plugin_register_enum) IA__thunarx_provider_plugin_register_enum __attribute((visibility("hidden")));
#define thunarx_provider_plugin_register_enum IA__thunarx_provider_plugin_register_enum

extern __typeof (thunarx_provider_plugin_register_flags) IA__thunarx_provider_plugin_register_flags __attribute((visibility("hidden")));
#define thunarx_provider_plugin_register_flags IA__thunarx_provider_plugin_register_flags

#endif
#endif
#if IN_HEADER(__THUNARX_RENAMER_H__)
#if IN_SOURCE(__THUNARX_RENAMER_C__)
extern __typeof (thunarx_renamer_get_type) IA__thunarx_renamer_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunarx_renamer_get_type IA__thunarx_renamer_get_type

extern __typeof (thunarx_renamer_get_help_url) IA__thunarx_renamer_get_help_url __attribute((visibility("hidden")));
#define thunarx_renamer_get_help_url IA__thunarx_renamer_get_help_url

extern __typeof (thunarx_renamer_set_help_url) IA__thunarx_renamer_set_help_url __attribute((visibility("hidden")));
#define thunarx_renamer_set_help_url IA__thunarx_renamer_set_help_url

extern __typeof (thunarx_renamer_get_name) IA__thunarx_renamer_get_name __attribute((visibility("hidden")));
#define thunarx_renamer_get_name IA__thunarx_renamer_get_name

extern __typeof (thunarx_renamer_set_name) IA__thunarx_renamer_set_name __attribute((visibility("hidden")));
#define thunarx_renamer_set_name IA__thunarx_renamer_set_name

extern __typeof (thunarx_renamer_process) IA__thunarx_renamer_process __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define thunarx_renamer_process IA__thunarx_renamer_process

extern __typeof (thunarx_renamer_save) IA__thunarx_renamer_save __attribute((visibility("hidden")));
#define thunarx_renamer_save IA__thunarx_renamer_save

extern __typeof (thunarx_renamer_load) IA__thunarx_renamer_load __attribute((visibility("hidden")));
#define thunarx_renamer_load IA__thunarx_renamer_load

extern __typeof (thunarx_renamer_get_actions) IA__thunarx_renamer_get_actions __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define thunarx_renamer_get_actions IA__thunarx_renamer_get_actions

extern __typeof (thunarx_renamer_changed) IA__thunarx_renamer_changed __attribute((visibility("hidden")));
#define thunarx_renamer_changed IA__thunarx_renamer_changed

#endif
#endif
#if IN_HEADER(__THUNARX_RENAMER_PROVIDER_H__)
#if IN_SOURCE(__THUNARX_RENAMER_PROVIDER_C__)
extern __typeof (thunarx_renamer_provider_get_type) IA__thunarx_renamer_provider_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define thunarx_renamer_provider_get_type IA__thunarx_renamer_provider_get_type

extern __typeof (thunarx_renamer_provider_get_renamers) IA__thunarx_renamer_provider_get_renamers __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define thunarx_renamer_provider_get_renamers IA__thunarx_renamer_provider_get_renamers

#endif
#endif

#endif /* HAVE_GNUC_VISIBILITY */
