/* Generated by make-thunarx-alias.pl. Do not edit this file. */

#ifdef HAVE_GNUC_VISIBILITY

#include <glib.h>

#undef IN_HEADER
#define IN_HEADER(x) 1

#undef IN_SOURCE
#define IN_SOURCE defined

#if IN_HEADER(__THUNARX_CONFIG_H__)
#if IN_SOURCE(__THUNARX_CONFIG_C__)
#undef thunarx_major_version 
extern __typeof (thunarx_major_version) thunarx_major_version __attribute((alias("IA__thunarx_major_version"), visibility("default")));

#undef thunarx_minor_version 
extern __typeof (thunarx_minor_version) thunarx_minor_version __attribute((alias("IA__thunarx_minor_version"), visibility("default")));

#undef thunarx_micro_version 
extern __typeof (thunarx_micro_version) thunarx_micro_version __attribute((alias("IA__thunarx_micro_version"), visibility("default")));

#undef thunarx_check_version 
extern __typeof (thunarx_check_version) thunarx_check_version __attribute((alias("IA__thunarx_check_version"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNARX_FILE_INFO_H__)
#if IN_SOURCE(__THUNARX_FILE_INFO_C__)
#undef thunarx_file_info_get_type 
extern __typeof (thunarx_file_info_get_type) thunarx_file_info_get_type __attribute((alias("IA__thunarx_file_info_get_type"), visibility("default")));

#undef thunarx_file_info_get_name 
extern __typeof (thunarx_file_info_get_name) thunarx_file_info_get_name __attribute((alias("IA__thunarx_file_info_get_name"), visibility("default")));

#undef thunarx_file_info_get_uri 
extern __typeof (thunarx_file_info_get_uri) thunarx_file_info_get_uri __attribute((alias("IA__thunarx_file_info_get_uri"), visibility("default")));

#undef thunarx_file_info_get_parent_uri 
extern __typeof (thunarx_file_info_get_parent_uri) thunarx_file_info_get_parent_uri __attribute((alias("IA__thunarx_file_info_get_parent_uri"), visibility("default")));

#undef thunarx_file_info_get_uri_scheme 
extern __typeof (thunarx_file_info_get_uri_scheme) thunarx_file_info_get_uri_scheme __attribute((alias("IA__thunarx_file_info_get_uri_scheme"), visibility("default")));

#undef thunarx_file_info_get_mime_type 
extern __typeof (thunarx_file_info_get_mime_type) thunarx_file_info_get_mime_type __attribute((alias("IA__thunarx_file_info_get_mime_type"), visibility("default")));

#undef thunarx_file_info_has_mime_type 
extern __typeof (thunarx_file_info_has_mime_type) thunarx_file_info_has_mime_type __attribute((alias("IA__thunarx_file_info_has_mime_type"), visibility("default")));

#undef thunarx_file_info_is_directory 
extern __typeof (thunarx_file_info_is_directory) thunarx_file_info_is_directory __attribute((alias("IA__thunarx_file_info_is_directory"), visibility("default")));

#undef thunarx_file_info_get_vfs_info 
extern __typeof (thunarx_file_info_get_vfs_info) thunarx_file_info_get_vfs_info __attribute((alias("IA__thunarx_file_info_get_vfs_info"), visibility("default")));

#undef thunarx_file_info_changed 
extern __typeof (thunarx_file_info_changed) thunarx_file_info_changed __attribute((alias("IA__thunarx_file_info_changed"), visibility("default")));

#undef thunarx_file_info_renamed 
extern __typeof (thunarx_file_info_renamed) thunarx_file_info_renamed __attribute((alias("IA__thunarx_file_info_renamed"), visibility("default")));

#undef thunarx_file_info_list_get_type 
extern __typeof (thunarx_file_info_list_get_type) thunarx_file_info_list_get_type __attribute((alias("IA__thunarx_file_info_list_get_type"), visibility("default")));

#undef thunarx_file_info_list_copy 
extern __typeof (thunarx_file_info_list_copy) thunarx_file_info_list_copy __attribute((alias("IA__thunarx_file_info_list_copy"), visibility("default")));

#undef thunarx_file_info_list_free 
extern __typeof (thunarx_file_info_list_free) thunarx_file_info_list_free __attribute((alias("IA__thunarx_file_info_list_free"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNARX_MENU_PROVIDER_H__)
#if IN_SOURCE(__THUNARX_MENU_PROVIDER_C__)
#undef thunarx_menu_provider_get_type 
extern __typeof (thunarx_menu_provider_get_type) thunarx_menu_provider_get_type __attribute((alias("IA__thunarx_menu_provider_get_type"), visibility("default")));

#undef thunarx_menu_provider_get_file_actions 
extern __typeof (thunarx_menu_provider_get_file_actions) thunarx_menu_provider_get_file_actions __attribute((alias("IA__thunarx_menu_provider_get_file_actions"), visibility("default")));

#undef thunarx_menu_provider_get_folder_actions 
extern __typeof (thunarx_menu_provider_get_folder_actions) thunarx_menu_provider_get_folder_actions __attribute((alias("IA__thunarx_menu_provider_get_folder_actions"), visibility("default")));

#undef thunarx_menu_provider_get_dnd_actions 
extern __typeof (thunarx_menu_provider_get_dnd_actions) thunarx_menu_provider_get_dnd_actions __attribute((alias("IA__thunarx_menu_provider_get_dnd_actions"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNARX_PREFERENCES_PROVIDER_H__)
#if IN_SOURCE(__THUNARX_PREFERENCES_PROVIDER_C__)
#undef thunarx_preferences_provider_get_type 
extern __typeof (thunarx_preferences_provider_get_type) thunarx_preferences_provider_get_type __attribute((alias("IA__thunarx_preferences_provider_get_type"), visibility("default")));

#undef thunarx_preferences_provider_get_actions 
extern __typeof (thunarx_preferences_provider_get_actions) thunarx_preferences_provider_get_actions __attribute((alias("IA__thunarx_preferences_provider_get_actions"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNARX_PROPERTY_PAGE_H__)
#if IN_SOURCE(__THUNARX_PROPERTY_PAGE_C__)
#undef thunarx_property_page_get_type 
extern __typeof (thunarx_property_page_get_type) thunarx_property_page_get_type __attribute((alias("IA__thunarx_property_page_get_type"), visibility("default")));

#undef thunarx_property_page_new 
extern __typeof (thunarx_property_page_new) thunarx_property_page_new __attribute((alias("IA__thunarx_property_page_new"), visibility("default")));

#undef thunarx_property_page_new_with_label_widget 
extern __typeof (thunarx_property_page_new_with_label_widget) thunarx_property_page_new_with_label_widget __attribute((alias("IA__thunarx_property_page_new_with_label_widget"), visibility("default")));

#undef thunarx_property_page_get_label 
extern __typeof (thunarx_property_page_get_label) thunarx_property_page_get_label __attribute((alias("IA__thunarx_property_page_get_label"), visibility("default")));

#undef thunarx_property_page_set_label 
extern __typeof (thunarx_property_page_set_label) thunarx_property_page_set_label __attribute((alias("IA__thunarx_property_page_set_label"), visibility("default")));

#undef thunarx_property_page_get_label_widget 
extern __typeof (thunarx_property_page_get_label_widget) thunarx_property_page_get_label_widget __attribute((alias("IA__thunarx_property_page_get_label_widget"), visibility("default")));

#undef thunarx_property_page_set_label_widget 
extern __typeof (thunarx_property_page_set_label_widget) thunarx_property_page_set_label_widget __attribute((alias("IA__thunarx_property_page_set_label_widget"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNARX_PROPERTY_PAGE_PROVIDER_H__)
#if IN_SOURCE(__THUNARX_PROPERTY_PAGE_PROVIDER_C__)
#undef thunarx_property_page_provider_get_type 
extern __typeof (thunarx_property_page_provider_get_type) thunarx_property_page_provider_get_type __attribute((alias("IA__thunarx_property_page_provider_get_type"), visibility("default")));

#undef thunarx_property_page_provider_get_pages 
extern __typeof (thunarx_property_page_provider_get_pages) thunarx_property_page_provider_get_pages __attribute((alias("IA__thunarx_property_page_provider_get_pages"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNARX_PROVIDER_FACTORY_H__)
#if IN_SOURCE(__THUNARX_PROVIDER_FACTORY_C__)
#undef thunarx_provider_factory_get_type 
extern __typeof (thunarx_provider_factory_get_type) thunarx_provider_factory_get_type __attribute((alias("IA__thunarx_provider_factory_get_type"), visibility("default")));

#undef thunarx_provider_factory_get_default 
extern __typeof (thunarx_provider_factory_get_default) thunarx_provider_factory_get_default __attribute((alias("IA__thunarx_provider_factory_get_default"), visibility("default")));

#undef thunarx_provider_factory_list_providers 
extern __typeof (thunarx_provider_factory_list_providers) thunarx_provider_factory_list_providers __attribute((alias("IA__thunarx_provider_factory_list_providers"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNARX_PROVIDER_PLUGIN_H__)
#if IN_SOURCE(__THUNARX_PROVIDER_PLUGIN_C__)
#undef thunarx_provider_plugin_get_type 
extern __typeof (thunarx_provider_plugin_get_type) thunarx_provider_plugin_get_type __attribute((alias("IA__thunarx_provider_plugin_get_type"), visibility("default")));

#undef thunarx_provider_plugin_get_resident 
extern __typeof (thunarx_provider_plugin_get_resident) thunarx_provider_plugin_get_resident __attribute((alias("IA__thunarx_provider_plugin_get_resident"), visibility("default")));

#undef thunarx_provider_plugin_set_resident 
extern __typeof (thunarx_provider_plugin_set_resident) thunarx_provider_plugin_set_resident __attribute((alias("IA__thunarx_provider_plugin_set_resident"), visibility("default")));

#undef thunarx_provider_plugin_register_type 
extern __typeof (thunarx_provider_plugin_register_type) thunarx_provider_plugin_register_type __attribute((alias("IA__thunarx_provider_plugin_register_type"), visibility("default")));

#undef thunarx_provider_plugin_add_interface 
extern __typeof (thunarx_provider_plugin_add_interface) thunarx_provider_plugin_add_interface __attribute((alias("IA__thunarx_provider_plugin_add_interface"), visibility("default")));

#undef thunarx_provider_plugin_register_enum 
extern __typeof (thunarx_provider_plugin_register_enum) thunarx_provider_plugin_register_enum __attribute((alias("IA__thunarx_provider_plugin_register_enum"), visibility("default")));

#undef thunarx_provider_plugin_register_flags 
extern __typeof (thunarx_provider_plugin_register_flags) thunarx_provider_plugin_register_flags __attribute((alias("IA__thunarx_provider_plugin_register_flags"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNARX_RENAMER_H__)
#if IN_SOURCE(__THUNARX_RENAMER_C__)
#undef thunarx_renamer_get_type 
extern __typeof (thunarx_renamer_get_type) thunarx_renamer_get_type __attribute((alias("IA__thunarx_renamer_get_type"), visibility("default")));

#undef thunarx_renamer_get_help_url 
extern __typeof (thunarx_renamer_get_help_url) thunarx_renamer_get_help_url __attribute((alias("IA__thunarx_renamer_get_help_url"), visibility("default")));

#undef thunarx_renamer_set_help_url 
extern __typeof (thunarx_renamer_set_help_url) thunarx_renamer_set_help_url __attribute((alias("IA__thunarx_renamer_set_help_url"), visibility("default")));

#undef thunarx_renamer_get_name 
extern __typeof (thunarx_renamer_get_name) thunarx_renamer_get_name __attribute((alias("IA__thunarx_renamer_get_name"), visibility("default")));

#undef thunarx_renamer_set_name 
extern __typeof (thunarx_renamer_set_name) thunarx_renamer_set_name __attribute((alias("IA__thunarx_renamer_set_name"), visibility("default")));

#undef thunarx_renamer_process 
extern __typeof (thunarx_renamer_process) thunarx_renamer_process __attribute((alias("IA__thunarx_renamer_process"), visibility("default")));

#undef thunarx_renamer_save 
extern __typeof (thunarx_renamer_save) thunarx_renamer_save __attribute((alias("IA__thunarx_renamer_save"), visibility("default")));

#undef thunarx_renamer_load 
extern __typeof (thunarx_renamer_load) thunarx_renamer_load __attribute((alias("IA__thunarx_renamer_load"), visibility("default")));

#undef thunarx_renamer_get_actions 
extern __typeof (thunarx_renamer_get_actions) thunarx_renamer_get_actions __attribute((alias("IA__thunarx_renamer_get_actions"), visibility("default")));

#undef thunarx_renamer_changed 
extern __typeof (thunarx_renamer_changed) thunarx_renamer_changed __attribute((alias("IA__thunarx_renamer_changed"), visibility("default")));

#endif
#endif
#if IN_HEADER(__THUNARX_RENAMER_PROVIDER_H__)
#if IN_SOURCE(__THUNARX_RENAMER_PROVIDER_C__)
#undef thunarx_renamer_provider_get_type 
extern __typeof (thunarx_renamer_provider_get_type) thunarx_renamer_provider_get_type __attribute((alias("IA__thunarx_renamer_provider_get_type"), visibility("default")));

#undef thunarx_renamer_provider_get_renamers 
extern __typeof (thunarx_renamer_provider_get_renamers) thunarx_renamer_provider_get_renamers __attribute((alias("IA__thunarx_renamer_provider_get_renamers"), visibility("default")));

#endif
#endif

#endif /* HAVE_GNUC_VISIBILITY */
