.\"     Title: Thunar
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 10/29/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "THUNAR" "1" "10/29/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
Thunar \- File Manager for the Xfce Desktop Environment
.SH "SYNOPSIS"
.HP 7
\fBThunar\fR [options] [[URI]...]
.HP 7
\fBThunar\fR [options] \-\-bulk\-rename [[URI]...]
.HP 7
\fBThunar\fR [options] \-\-quit
.SH "DESCRIPTION"
.PP

\fBThunar\fR
is a fast and easy to use file manager for the Xfce Desktop Environment\&. It has been designed from the ground up to be lighweight with special focus on usability\&. Its user interface is clean and intuitive, and does not include any confusing or useless options\&.
.SH "INVOCATION"
.PP

\fBThunar\fR
takes a list of
\fIURI\fRs for folders that should be opened in new file manager windows or files that should be run using the default application for their types\&. The
\fIURI\fRs may be specified as either
\fBfile:\fR
or
\fBtrash:\fR
URIs, absolute paths or paths relative to the current directory from which
\fBThunar\fR
is being invoked\&. If no
\fIURI\fRs are specified, the current folder will be opened in a new file manager window\&.
.PP
When the
\fB\-\-bulk\-rename\fR
option is specified no file managers windows will be opened, but instead the
\fIURI\fRs will be passed to the bulk renamer\&. The bulk renamer allows to rename several files or folders at once using different renamer modules\&.
.SS "Options"
.PP
\fB\-?\fR, \fB\-\-help\fR
.RS 4
Print brief help and exit\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Print version information and exit\&.
.RE
.PP
\fB\-B\fR, \fB\-\-bulk\-rename\fR
.RS 4
Open the
\fIURI\fRs in a standalone window of the bulk renamer\&.
.RE
.PP
\fB\-\-daemon\fR
.RS 4
Do not terminate the
\fBThunar\fR
instance when the last window is closed, but keep it running to speed up opening new windows later on\&. This is the default when spawning
\fBThunar\fR
as part of the default Xfce session or when using D\-Bus activation\&.
.RE
.PP
\fB\-\-display=DISPLAY\fR
.RS 4
Use the specified X
\fBDISPLAY\fR
for the user interface\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quit\fR
.RS 4
Terminate any
\fBThunar\fR
instance running in the background (spawned using the
\fB\-\-daemon\fR
option)\&. This command should be used whenever
\fBThunar\fR
is upgraded to a new version to ensure that no old instance is reused\&.
.RE
.SH "AUTHOR"
.PP

\fBThunar\fR
was written by Benedikt Meurer
<benny@xfce\&.org>\&.
.PP
This manual page was written by Benedikt Meurer
<benny@xfce\&.org>\&.
